[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.42.0",
    "flask>=3.1.0",
    "openai>=1.59.6",
    "requests>=2.32.3",
    "slack-bolt>=1.22.0",
]
